@startuml
'Domænemodellen giver nye entity klasser
'Pakker, model og util
!pragma layout smetana

class Main
class StartMenu
class User
class DataValidator
class CreateAccount
class WatchList
class MainMenu
abstract Media
class TvShows
class Movies
class MediaWindow
class Category


package "util"{
       class TextUI
       class DbIO
}

Main *-- StartMenu
StartMenu *-- User
User *-- DataValidator
User *-- CreateAccount
StartMenu *-- MainMenu
MainMenu *-- WatchList
MainMenu *-- Media
Media *-- Movies
Media *-- TvShows
MainMenu *-- MediaWindow
StartMenu *-- util
MainMenu *-- Category

Main : + static void main(string [] args)

StartMenu : + CreateAccount
'---_new-----
StartMenu : - login()
'-----------

User : - Private String Username
User : - Private String Password
User : - static ArrayList <User> users
'---_new-----
User : + User(String Username, String Password)

'-----------
DataValidator : - String Username
DataValidator : - String Password
'---_new-----
DataValidator : + Boolean isUsernameValid()
DataValidator : + Boolean isPassWordValid()
'-----------

CreateAccount : - Boolean createUser(String name, String Password)
CreateAccount : - Boolean add.User(new user(name, Password)

WatchList : + addMedia()
WatchList : + displayWatched()
WatchList : + removeMedia()

MainMenu : + Category
MainMenu : + WatchList
'---_new-----
MainMenu : + search()
MainMenu : + logOut()
'-----------

Media : + String Title
Media : + int Release Year
Media : + float Rating
Media : + String Genre
Media : + int timeWatched
'---_new-----
Media : + addMedia(String title, int releaseYear, float rating, String genre, boolean MediaType)
Media : + moveToWatchList()
'-----------

TvShows : + int seasons
TvShows : + int episodes

MediaWindow : + playMedia()
MediaWindow : + pauseMedia()
MediaWindow : + rewindMedia()
MediaWindow : + exitMedia()
MediaWindow : + chooseSeAndEp()

Category : + chooseGenre()
Category : + chooseYear()

DbIO : - Scanner scanner
'---_new-----
DbIO : + Arraylist<User> readUserData(String path)
DbIO : + void saveUserData(ArrayList<User> users)
DbIO : + String[] readLoginData(String Username, String password)
'-----------

TextUI : + String getInput(String msg)
TextUI : - Scanner scanner
TextUI : + void displayMessage(String msg)

@enduml
